#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d  󰳫  󰖟  󰊗 

bspc config border_width         2
bspc config window_gap          10

bspc config automatic_scheme alternate
bspc config split_ratio           0.62
bspc config focus_follows_pointer true
bspc config single_monocle        true
bspc config borderless_monocle    true

bspc config normal_border_color "#6C6C6C"
bspc config active_border_color "#BCBCBC"
bspc config focused_border_color "#BCBCBC"
bspc config presel_feedback_color "#BCBCBC"

bspc rule -a Screenkey manage=off
bspc rule -a zenity state=floating follow=off border=off

feh --bg-fill Загрузки/wallhaven-p9rpv3.jpg &
# .config/conky/Athebyne/start.sh &
polybar &
dunst &
