#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d  󰳫  󰖟  󰊗 

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio           0.50
bspc config focus_follows_pointer true
bspc config single_monocle        true
bspc config borderless_monocle    true

bspc rule -a Screenkey manage=off

feh --bg-fill Загрузки/wallhaven-p9qovj.jpg &
# .config/conky/Athebyne/start.sh &
polybar &
dunst &
